title: Practice QA
description: Software testing and automation interview questions
theme: minima
baseurl: "/practiceqa"
url: "https://shajeebsh.github.io"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
